language: node_js
node_js:
  - node
  - lts/*
  - 10.13
  - 8
  - 6
before_install:
  - npm i -g yarn@$(jq '.engines.yarn' package.json --raw-output)
  - export PATH="$(npm -g bin)/.yarn/bin:$PATH"
install:
  - yarn install --ignore-engines
before_script:
  - yarn lint
cache:
  yarn: true